name: build

on: [push]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Install ğŸ”§
        run: npm install
      - name: Lint ğŸ”
        run: npm run lint
      - name: Test âœ”ï¸
        run: npm test
      - name: Cleanup ğŸ§¹
        run: |
          # Discarding dev dependencies to only retain prod ones:
          npm prune --production
          echo OK1
          # Workaround while waiting for: https://github.com/peaceiris/actions-gh-pages/issues/163#issuecomment-612063865
          git add -f node_modules
          echo OK2
          git status
          echo OK3
      - name: Deploy ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
