name: build

on: [push]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Install ğŸ”§
        run: npm install
      - name: Lint ğŸ”
        run: npm run lint
      - name: Test â˜‘
        run: npm test
      - name: Cleanup ğŸ§¹
        # Discarding dev dependencies to only retain prod ones:
        run: npm prune --production
      - name: Deploy ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        # Workaround while waiting for: https://github.com/peaceiris/actions-gh-pages/issues/163#issuecomment-612063865
        run: git add -f node_modules && git status
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
